### ISSUE TITLE
Check the postbyte encoding for EXG, TFR, PSH and PUL

### ISSUE THREAD

**Issue by jotego** [JTFPGA/jtkcpu#12]
The postbyte encoding for EXG, TFR, PSH and PUL could be different for the M6809 abd the K-CPU. Compare them bit by bit. If different, report to Alfred.

**Comment by florgana** [comment]
About PSH and PUL is still the same as in the M6809.

**Comment by florgana** [comment]
About the TFR/EXG, in Konami only combine 6 register fields: a, b, x, y, s and u, in the post-byte it is read in reverse, the 4 least significant bits are the source and the 4 most significant bits are destination.

Added to the document the new TFR/EXG postbyte

**Comment by jotego** [comment]
How do you load data in DP then?

**Comment by florgana** [comment]
The DP register is updated with the stack.
