### ISSUE TITLE
difference between CLR and CLRW?

### ISSUE THREAD

**Issue by jotego** [JTFPGA/jtkcpu#14]
All the W instructions have indexed addressing counterparts, like LSR and LSRW.
I don't see any W instructions in the debug code of MAME for ajax, hcastle, simpsons...
Are you sure these are supported in this CPU? And what is the difference with the other ones?

**Comment by florgana** [comment]
The differences is that the indexed instructions operate on 8 bits and the W are 16 bit operations

**Comment by jotego** [comment]
That makes sense! Thanks
