### ISSUE TITLE
alu: separate op decoding from execution

### ISSUE THREAD

**Issue by jotego** [JTFPGA/jtkcpu#15]
Right now the same `case` decodes the op directly into the `rslt`. This makes the combinational logic chain longer to go from an 8-bit op value to a 16-bit result value that also depends on other 8 or 16-bit operands.

It is better to break this in two steps:

1. Decode op to a hot-one encoding for the ALU operation. Register that hot-one value
2. Decode the hot-one to resolve `rslt`

It will look like this:

```
reg [ ... :0] aluhot;

always @(posedge clk) begin
    case (op)
        STA,  STB,  STD,
        STX,  STY,  STU,  STS,
        LEAX, LEAY, LEAU, LEAS: aluhot = 'h1;

        LDA_IMM,LDB_IMM,LDA_IDX,LDB_IDX,TSTA,TSTB,TST,LDD_IMM,LDD_IDX,LDX_IMM,
        LDX_IDX,LDY_IMM,LDY_IDX,LDU_IMM,LDU_IDX,LDS_IMM,LDS_IDX,TSTD,TSTW: aluhot = 'h2;

        // etc
    endcase
end

always @* begin
    case( aluhot )
        'h1: begin
            rslt  = opnd0;
            v_out = 0;   
        end
        'h2: begin
            rslt  = opnd1;
            v_out = 0;
        end
    endcase
    // etc
end
```

This change will increase Fmax

**Comment by florgana** [comment]
Done!
