### ISSUE TITLE
carry out wrong for 8-bit operations

### ISSUE THREAD

**Issue by jotego** [JTFPGA/jtkcpu#4]
Separate in 8 and 16 bit cases. Then you'll be able to delete the **if** statement.
https://github.com/JTFPGA/jtkcpu/blob/7f9acf87792ee685a2f60aa51b8fcd6c7923718a/hdl/jtkcpu_alu.v#L88

**Comment by florgana** [comment]
Done!
The addition was separated into 8 bit and 16 bit and was removed the conditional IF
