### ISSUE TITLE
Wrong conditional

### ISSUE THREAD

**Issue by jotego** [JTFPGA/jtkcpu#5]
That conditional won't work. That mistake is made in other places too. Delete this **if** when you separate the addition in 8/16 bit parts.

https://github.com/JTFPGA/jtkcpu/blob/7f9acf87792ee685a2f60aa51b8fcd6c7923718a/hdl/jtkcpu_alu.v#L91

**Comment by florgana** [comment]
Done! 
The addition was separated into 8 bit and 16 bit and this conditional was removed
