### ISSUE TITLE
Use a signal for ucode where possible

### ISSUE THREAD

**Issue by jotego** [JTFPGA/jtkcpu#7]
The long comparison for all 16-bit operations may be shortened by using signals from the ucode that indicate 16-bit length instead of comparing with so many op codes.

https://github.com/JTFPGA/jtkcpu/blob/7f9acf87792ee685a2f60aa51b8fcd6c7923718a/hdl/jtkcpu_alu.v#L41

**Comment by florgana** [comment]
Done! 
The 16-bit operations that are in the ucode were eliminated and the rest were ordered
